exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
exception in lookup_func list index out of range
Traceback (most recent call last):
  File "training/batch_cache.py", line 186, in lookup_func
    path = self.image_paths[key[0]][ind + dd]
IndexError: list index out of range
